-- Script para configurar las tablas del SGA en Supabase

-- 1. Tabla de Inventario
CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  stock FLOAT DEFAULT 0,
  unit TEXT DEFAULT 'kg',
  price FLOAT DEFAULT 0,
  expiry DATE,
  status TEXT DEFAULT 'ok',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Tabla de Desperdicios
CREATE TABLE waste (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES inventory(id),
  name TEXT NOT NULL,
  amount FLOAT NOT NULL,
  cost FLOAT NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Habilitar acceso público rápido (Solo para desarrollo, en producción usar RLS)
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON inventory FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE waste ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON waste FOR ALL USING (true) WITH CHECK (true);
